demo:
  target: dw
  outputs:
    dw:
      type: snowflake
      account: 'not needed'
      user: '{{ env_var("DBT_CURRENT_USER") }}'
      role: accountadmin
      database: '{{ env_var("DBT_CURRENT_DB") }}'
      schema: edw
      warehouse: compute_wh
      threads: '{{ env_var("DBT_THREADS") | int }}'